[_]
schema-version = "0.2"

[[io.buildpacks.group]]
uri = "heroku/nodejs"

[[io.buildpacks.group]]
uri = "heroku/procfile"

[[io.buildpacks.build.env]]
name = "VITE_CLERK_PUBLISHABLE_KEY"
value = "pk_test_bGl2aW5nLWtpd2ktNTg5Ni5jbGVyay5hY2NvdW50cy5kZXYk"
